# Generated by Django 6.0.4 on 2026-04-21 16:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercise_user_avatar_user_bio_session_exerciseset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='base_coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation'), ('machine', 'Machine'), ('bodyweight', 'Bodyweight'), ('yoga', 'Yoga')], default='compound', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='target_muscle',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('shoulders', 'Shoulders'), ('forearm', 'Forearm'), ('quads', 'Quads'), ('glutes', 'Glutes'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('abs', 'Abs'), ('yoga', 'Yoga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='lastset',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
